project:
  type: website
  output-dir: docs

website:
  title: "Shakil A. Rafi, PhD"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - experience.qmd
      - projects.qmd

      

format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true

editor: visual

