Here is a list of various talks and papers I have had over the years.

#### Talks

-   *Neural Networks for Approximating the Heat Equations.* PhD Thesis, March 2024.

-   *Maximal Parameter Estimates for Neural Networks and Uncertainties in Approximation.* SIAM Conference on Uncertainty Quantification '24. Trieste, Italy.

-   *SOM-Where in Chicago: What self-organizing maps tell us about rideshares in Chicago*, OAK Fall 2023 Conference on Supercomputing, October, 2023.

-   *Modal Logic and the Multiverse of Madness*, Graduate Student Colloquium, 2023

-   *Why Knot Theorists are Unsure about Tying Shoelaces.*, Graduate Student Colloquium, February, 2022

-   *Heegard Splittings and Basic Theorems About Them.* Graduate Student Colloquium, Septermber 2020

-   *Topology and Computation.*Graduate Student Colloquium, January 2020

-   *Turing Machines and the Halting Problem.* MAA Regional MathFest Troy University, Troy, AL

-   *An algorithm for determining congruency between n-regular polygons.*MAA National MathFest 2014, Portland, OR

------------------------------------------------------------------------

#### Papers and Pre-prints

-   *Towards an Algebraic Framework for Approximating Functions Using Neural Network Polynomials.* Rafi S., Padgett, J. L., Nakarmi U. Pre-print [here](https://doi.org/10.48550/arXiv.2402.01058)

-   *A Random Walk Down Maternity*. Internal white-paper produced summarizing my work during my internship at Arkansas Blue Cross and Blue Shield.

-   *Who got loans during the the pandemic? Class, race and gender inequality in the Paycheck Protection Program*. Pre-print: [here](https://www.preprints.org/manuscript/202309.0654/v1)

-   *Who Rides Uber Anyway*: A census tract level analysis and clustering of ride-share for the city of Chicago during the era of the pandemic. Shakil Rafi & Arna Nithila. Preprint: [here](https://www.techrxiv.org/articles/preprint/Who_rides_Uber_anyway_A_census-tract_level_analysis_and_clustering_of_ride-shares_for_the_city_of_Chicago_during_the_era_of_the_pandemic/21076042/2)

-   *An algorithm to determine congruency between two n-regular polygons.* Conference Paper submitted to the MAA Mathfest 2014, in Portland, OR Pre-print: [here](https://www.preprints.org/manuscript/202303.0490/v1)

-   *Is it worth going outside the cave?* Unpublished. Partial fulfillment for Philosophy requirements.

-   *Nightvale and Existentialism.* Unpublished. Partial fulfilmment for Philosophy requirements.

------------------------------------------------------------------------

#### Workshops

-   *Arkansas Summer Research Institute 2022* In the Summer of 2022 I attended the Arkansas Summer Research Institute. This is an NSF EPSCOR funded workshop aiming to bring promising students from across two dozen different states to provide hands-on experience on real-life machine learning and data science applications.

<!-- -->

-   *Mathematical Sciences Research Institute / Simons-Laufer Mathematical Scinces Institute* In the summer of 2023 I was honored to participate in the MSRI/SLMath Summer Graduate School on Machine Learning hosted at UC San Diego. Our cohort consisted of students from across the world, including South Korea, Spain, and Togo. Our workshops featured hands on experience with neural networks and lectures on the cutting edge of machine learning, such as overparametrization and adversarial patterns in computer vision.

------------------------------------------------------------------------

#### Posters

-   *Maximal Parameter Estimates for Neural Networks and Uncertainties in Approximation*. **SIAM Conference on Uncertainty Quantification, Trieste, Italy**We take a structural description of neural networks first proposed by Peterson and Voightlander, 2019 and further built upon by Grohs et. al, 2020, and further extend this neural network calculus. Along the way we rebuild several bits of well-known machinery in the language of neural networks and show that yes, indeed, parameter estimates are bounded polynomially on the precision of our estimates. We give: 1.Neural network architectures representing Taylor polynomials and $e^x$. 2. Neural network architectures that are able to simulate a highly modified Monte Carlo sampling from Brownian motions along the function support 3. Neural network estimates for trapezoidal rule 4. And finally for the first time, that neural networks without too many (defined as being polynomial on the precision) parameters may be able to approximate a modified diffusion equation. This adds to the literature in that it builds upon a much needed need to formally axiomatize neural networks, both in terms of the number of parameters and exactly how expressive it can be. Minimal parameter estimates mean neural networks will be more accessible in smaller computing devices, meaning greater access for more people to this amazing technology and it means that more efficient neural networks can be built which reduce environmental impact as we march forward into a more artificial intelligence focused age.

-   *A Census Tract based clustering analysis of ride-shareing behavior or Chicago residents during the era of the pandemic* **Arkansas Spring Lecture Series 2022, Fayetteville, AR**This a presentation of the work upto that time, on segmenting the customers in ride-sharing apps such as Chicago during the year 2020. Held once a year, the Arkansas Spring Lecture Series is a conference bringing together mathematicians from across the world to present the very latest in their research. The theme this year was data science, and featured among others Dr. Yousef Saad, Dr. Sabine van Huffel and Dr. Jack Dongara. It is funded by the University of Arkansas and the NSF.

-   *An analysis of customer behavior in ride-sharing apps during the era of the pandemic* **SIAM Mathematics of Data Science San Diego, CA** We take the work presented earlier in the Arkansas Spring Lecture Series and expand on that. Held every year the Mathematics of Data Science Conference MDS 22 seeks to bring the cutting edge of data science from across the world into one conference. A pre-print can be found [here](https://www.techrxiv.org/articles/preprint/Who_rides_Uber_anyway_A_census-tract_level_analysis_and_clustering_of_ride-shares_for_the_city_of_Chicago_during_the_era_of_the_pandemic/21076042/2)
